Help field for the rule buttons
datx02-21-16/datx02 pull request #30
Opened 2021-04-11 18:16 UTC by tessagon

Nu finns knappar för alla regler (om jag inte missat någon av misstag) och när man klickar på dessa får man info om regeln i form av sequent för regeln och en hjälptext som beskriver hur den fungerar. Utseendemässigt är det kanske inte så fantastikt men jag får verkligen inte till något bättre när jag försökt nu under helgen. Någon annan får gärna försöka sig på att förbättra det.

2021-04-12 15:03 UTC, freddyabrahamsson requested changes

2021-04-12 15:03 UTC, freddyabrahamsson commented on src/GUI/RulesPanel.purs
> +              ]
Detta borde gå att skriva om som funktioner av de faktiska reglerna (en `show`, en `sequent` och en `textualHint`) alla med typen `RuleType -> String`. Som det är nu så är funktionen beroende av att man lägger sakerna i samma ordning i de inblandade arrayerna.

2021-04-12 21:27 UTC, tessagon commented on src/GUI/RulesPanel.purs
> +              ]
Fixat.

2021-04-12 21:28 UTC, tessagon commented on src/sass/mystyles.scss
> +}
Fixat.

2021-04-12 21:29 UTC, tessagon commented on src/sass/mystyles.scss
> +}
Knapparna ligger i kolumner nu men de fyller inte ut kolumnerna. Jag vet inte hur jag ska fixa det, jag har försökt testa olika Bulma klasser men ingenting verkar göra någon skillnad trots att jag har importerat css klasserna.

2021-04-12 22:26 UTC, freddyabrahamsson commented on src/sass/mystyles.scss
> +}
Föreslagen lösning finns i 20956f0b636813a59ddb1ea1478399ce6848021d.

2021-04-14 10:07 UTC, freddyabrahamsson approved these changes

2021-04-14 10:08 UTC, merged